name: fino
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 
  provider:
  flutter_svg:
  gap:
  bounce: 
  shared_preferences:
  flutter_screenutil: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/RalewayRegular.ttf
          weight: 400
        - asset: assets/fonts/RalewayMedium.ttf
          weight: 500
        - asset: assets/fonts/RalewaySemiBold.ttf
          weight: 600
        - asset: assets/fonts/RalewayBold.ttf
          weight: 700
        - asset: assets/fonts/RalewayExtraBold.ttf
          weight: 800
        - asset: assets/fonts/RalewayBlack.ttf
          weight: 900


flutter_assets:
  assets_path: assets/
  output_path: lib\core\utils\
  filename: assets.dart
  field_prefix: ""
